// NASA & International Spacecraft Registry (§Master Build Phase 2)
// Comprehensive catalog of real-world spacecraft with verified NASA / JPL / ESA / JAXA source citations.
// Strict separation between official real-world specifications and Mission Forge game simulation models.

export interface RegistrySpacecraft {
  id: string;
  name: string;
  agency: string;
  craftType: "Orbiter" | "Lander / Rover" | "Flyby" | "Atmospheric Probe" | "Crew Vehicle" | "Space Observatory";
  category: "lunar" | "mars" | "asteroids" | "jupiter" | "saturn" | "outer" | "telescopes";
  destination: string;
  launchYear: number;
  status: "Active" | "Completed" | "En Route" | "Interstellar";
  missionDuration: string;
  missionPurpose: string;
  majorInstruments: string[];
  realSpecs: {
    launchMassKg: number | string;
    propulsion: string;
    power: string;
    communication: string;
    propellantMassKg?: number | string;
    missionCost?: string;
  };
  gameModel: {
    engineClass: string;
    massTier: string;
    powerType: string;
    instrumentEquivalents: string[];
    simulationNotes: string;
  };
  whyItMatters: string;
  officialSource: string;
  sourceUrl: string;
  verified: boolean;
}

export const SPACECRAFT_REGISTRY: RegistrySpacecraft[] = [
  // --- LUNAR ---
  {
    id: "orion-artemis",
    name: "Orion MPCV",
    agency: "NASA / ESA",
    craftType: "Crew Vehicle",
    category: "lunar",
    destination: "Moon (Cislunar & NRHO)",
    launchYear: 2022,
    status: "Active",
    missionDuration: "Artemis I (25.5 days); multi-decade operational program",
    missionPurpose: "Exploration-class crew transport designed for deep-space missions to the Moon, Lunar Gateway, and Mars staging orbits.",
    majorInstruments: ["Optical Navigation Camera", "Hybrid Electronic Radiation Assessor (HERA)", "Active Dosimeters"],
    realSpecs: {
      launchMassKg: 25848,
      propulsion: "Aerojet AJ10-190 OMS-E (26.7 kN thrust, 312 s Isp) + 8 aux thrusters",
      power: "4 solar array wings (11.1 kW total at 1 AU)",
      communication: "Deep Space Network (DSN) Ka-band and S-band phased array",
      propellantMassKg: 8600,
    },
    gameModel: {
      engineClass: "Chemical Rocket (RL10 / Hydrolox analog in Mission Forge)",
      massTier: "Heavy Crew Vehicle (>25,000 kg)",
      powerType: "4x High-Efficiency Solar Wings",
      instrumentEquivalents: ["camera", "radiation"],
      simulationNotes: "Game models Orion's crew cabin, ESM service module, and modular fuel tanks for deep-space mission planning.",
    },
    whyItMatters: "Humanity's foundational deep-space spacecraft for returning astronauts to the lunar south pole under Artemis.",
    officialSource: "NASA Orion Reference Guide",
    sourceUrl: "https://www.nasa.gov/humans-in-space/orion-spacecraft/",
    verified: true,
  },
  {
    id: "apollo-csm",
    name: "Apollo Command / Service Module (CSM)",
    agency: "NASA",
    craftType: "Crew Vehicle",
    category: "lunar",
    destination: "Moon (Low Lunar Orbit & Landing)",
    launchYear: 1968,
    status: "Completed",
    missionDuration: "8 to 12 days per mission (Apollo 7–17)",
    missionPurpose: "Transported 3 astronauts from Earth orbit to lunar orbit, sustained them in cislunar space, and returned them safely to Earth.",
    majorInstruments: ["Mapping & Panoramic Cameras", "Gamma-Ray Spectrometer", "X-Ray Fluorescence Spectrometer"],
    realSpecs: {
      launchMassKg: 30320,
      propulsion: "Aerojet AJ10-137 Service Propulsion System (91 kN thrust, 314 s Isp)",
      power: "3 Pratt & Whitney Apollo fuel cells (H2/O2, 1.4 kW continuous each)",
      communication: "S-band unified radio, steerable high-gain parabolic antenna",
      propellantMassKg: 18410,
    },
    gameModel: {
      engineClass: "Chemical Cryogenic Engine",
      massTier: "Heavy Exploration Craft",
      powerType: "Primary Fuel Cell / Chemical Battery Architecture",
      instrumentEquivalents: ["camera", "spectrometer"],
      simulationNotes: "Inspired the mass-to-fuel ratio and high-thrust staging mechanics modeled in Mission Forge's Tsiolkovsky calculations.",
    },
    whyItMatters: "First spacecraft to carry humans out of low Earth orbit and into orbit around another celestial world.",
    officialSource: "NASA Apollo 11 Lunar Mission Press Kit (1969)",
    sourceUrl: "https://www.nasa.gov/mission_pages/apollo/missions/apollo11.html",
    verified: true,
  },
  {
    id: "lro",
    name: "Lunar Reconnaissance Orbiter (LRO)",
    agency: "NASA / GSFC",
    craftType: "Orbiter",
    category: "lunar",
    destination: "Moon (Low Lunar Polar Orbit)",
    launchYear: 2009,
    status: "Active",
    missionDuration: "15+ years (continuous operational extension)",
    missionPurpose: "Map lunar surface topography at high resolution, measure radiation dosage, and scout landing sites for human Artemis exploration.",
    majorInstruments: ["LROC (Narrow/Wide Angle Cameras)", "LOLA (Laser Altimeter)", "Diviner (Thermal Radiometer)", "LAMP (Lyman Alpha Mapping)"],
    realSpecs: {
      launchMassKg: 1916,
      propulsion: "Hydrazine monopropellant attitude control and orbit maintenance thrusters",
      power: "Single articulated solar wing (1,850 W) + Li-ion batteries",
      communication: "Ka-band high-rate transmitter (100–461 Mbps) to White Sands",
      propellantMassKg: 898,
    },
    gameModel: {
      engineClass: "Chemical Monopropellant Stationkeeping",
      massTier: "Medium Orbiter (~1,900 kg)",
      powerType: "Single High-Area Solar Wing + Battery Storage",
      instrumentEquivalents: ["camera", "radar", "radiation"],
      simulationNotes: "LRO's elevation topography data provides the physical altitude maps used in Mission Forge's lunar landing sequence.",
    },
    whyItMatters: "Provided the most detailed topographical maps ever produced of another world, proving the presence of water ice in permanently shadowed polar craters.",
    officialSource: "NASA LRO Project Fact Sheet",
    sourceUrl: "https://science.nasa.gov/mission/lro/",
    verified: true,
  },
  {
    id: "lunar-prospector",
    name: "Lunar Prospector",
    agency: "NASA / ARC",
    craftType: "Orbiter",
    category: "lunar",
    destination: "Moon (Low Lunar Polar Orbit)",
    launchYear: 1998,
    status: "Completed",
    missionDuration: "1.5 years",
    missionPurpose: "Low-cost Discovery-class lunar polar orbiter designed for surface composition mapping, gravity surveys, and magnetic field mapping.",
    majorInstruments: ["Neutron Spectrometer (NS)", "Gamma Ray Spectrometer (GRS)", "Magnetometer (MAG)", "Alpha Particle Spectrometer (APS)"],
    realSpecs: {
      launchMassKg: 296,
      propulsion: "Hydrazine monopropellant blowdown system",
      power: "Body-mounted cylindrical solar cells (220 W)",
      communication: "S-band transponder with omnidirectional antennas",
      propellantMassKg: 138,
    },
    gameModel: {
      engineClass: "Micro-Propulsion Monopropellant",
      massTier: "Compact Probe (<300 kg)",
      powerType: "Body-Mounted Solar Cell Array",
      instrumentEquivalents: ["spectrometer", "radiation"],
      simulationNotes: "Represents the mass-first lightweight mission architecture available under the 'Budget Tier 1' choice in Mission Forge.",
    },
    whyItMatters: "First spacecraft to detect signatures of hydrogen concentrated in the lunar polar regions, confirming prospective polar ice deposits.",
    officialSource: "NASA Ames Research Center Lunar Prospector Catalog",
    sourceUrl: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1998-001A",
    verified: true,
  },

  // --- MARS ---
  {
    id: "perseverance-rover",
    name: "Perseverance Rover & Ingenuity",
    agency: "NASA / JPL",
    craftType: "Lander / Rover",
    category: "mars",
    destination: "Mars (Jezero Crater)",
    launchYear: 2020,
    status: "Active",
    missionDuration: "4+ years on surface (ongoing Mars 2020 mission)",
    missionPurpose: "Search for signs of ancient biosignatures, characterize past Martian climate and geology, and collect hermetically sealed rock cores for return to Earth.",
    majorInstruments: ["Mastcam-Z", "SuperCam", "PIXL", "SHERLOC", "MOXIE (O2 generator)", "RIMFAX (Ground-Penetrating Radar)", "MEDA (Weather)"],
    realSpecs: {
      launchMassKg: 1025,
      propulsion: "Cruise stage bipropellant + Sky Crane hydrazine terminal descent engines",
      power: "Multi-Mission Radioisotope Thermoelectric Generator (MMRTG, ~110 W electric) + 2 Li-ion batteries",
      communication: "UHF to Mars orbiters (MRO/MAVEN) + X-band High Gain direct-to-Earth antenna",
    },
    gameModel: {
      engineClass: "Terminal Descent Thruster Stage",
      massTier: "Heavy Surface Rover (~1,025 kg)",
      powerType: "Radioisotope Thermoelectric Generator (RTG)",
      instrumentEquivalents: ["camera", "spectrometer", "radar", "radiation", "drill"],
      simulationNotes: "Mission Forge's Mars EDL sequence follows Perseverance's hypersonic entry, supersonic parachute deployment, and skycrane touchdown stages.",
    },
    whyItMatters: "Collects sample tubes that will be returned to Earth; also carried Ingenuity, the first powered aircraft to fly on another planet (72 successful flights).",
    officialSource: "NASA JPL Mars 2020 Mission Overview",
    sourceUrl: "https://mars.nasa.gov/mars2020/",
    verified: true,
  },
  {
    id: "curiosity-rover",
    name: "Curiosity Rover (MSL)",
    agency: "NASA / JPL",
    craftType: "Lander / Rover",
    category: "mars",
    destination: "Mars (Gale Crater)",
    launchYear: 2011,
    status: "Active",
    missionDuration: "12+ years on surface (ongoing operations)",
    missionPurpose: "Assess whether Mars ever had an environment capable of supporting microbial life (habitability investigation).",
    majorInstruments: ["Mastcam", "SAM (Sample Analysis at Mars)", "ChemCam", "CheMin", "RAD (Radiation Detector)", "DAN (Neutron albedo)", "REMS"],
    realSpecs: {
      launchMassKg: 899,
      propulsion: "Guided entry reaction control + 8 Sky Crane hydrazine engines",
      power: "1x MMRTG (~110 W electric at start of mission) + Li-ion battery peak shaving",
      communication: "Electra UHF relay to orbiters + X-band steerable high gain antenna",
    },
    gameModel: {
      engineClass: "Descent Thruster Stage",
      massTier: "Heavy Surface Science Rover",
      powerType: "MMRTG Plutonium-238 Generator",
      instrumentEquivalents: ["camera", "spectrometer", "radiation", "drill"],
      simulationNotes: "Direct inspiration for the 'RTG + Core Drill + Spectrometer' surface exploration configuration in Mission Forge.",
    },
    whyItMatters: "Proved that ancient Mars had liquid freshwater lakes with neutral pH, carbon, nitrogen, oxygen, phosphorus, and sulfur—all ingredients for life.",
    officialSource: "NASA Mars Science Laboratory / Curiosity",
    sourceUrl: "https://mars.nasa.gov/msl/",
    verified: true,
  },
  {
    id: "mro",
    name: "Mars Reconnaissance Orbiter (MRO)",
    agency: "NASA / JPL",
    craftType: "Orbiter",
    category: "mars",
    destination: "Mars (Low Sun-Synchronous Orbit)",
    launchYear: 2005,
    status: "Active",
    missionDuration: "19+ years in orbit",
    missionPurpose: "High-resolution orbital reconnaissance of Martian geology, atmospheric circulation, surface minerals, and high-bandwidth telecom relay.",
    majorInstruments: ["HiRISE (0.5m telescope)", "CRISM (Imaging Spectrometer)", "SHARAD (Subsurface Radar)", "MCS (Climate Sounder)", "MARCI"],
    realSpecs: {
      launchMassKg: 2180,
      propulsion: "20 x monopropellant hydrazine thrusters (total propellant 1,149 kg)",
      power: "2 solar array wings (2,000 W at Mars) + 2 Ni-H2 batteries",
      communication: "3-meter Cassegrain High Gain Antenna (Ka-band & X-band up to 6 Mbps)",
      propellantMassKg: 1149,
    },
    gameModel: {
      engineClass: "Chemical Bipropellant / Monopropellant",
      massTier: "Flagship Orbital Scout (>2,100 kg)",
      powerType: "Twin High-Area Solar Wings",
      instrumentEquivalents: ["camera", "spectrometer", "radar"],
      simulationNotes: "Demonstrates the orbital survey objective in Mission Forge, generating science value from orbit without risking surface entry.",
    },
    whyItMatters: "Has returned over 450 terabits of science data, discovering active avalanches, seasonal gullies, and ice sheets buried beneath dust.",
    officialSource: "NASA JPL MRO Mission Fact Sheet",
    sourceUrl: "https://science.nasa.gov/mission/mro/",
    verified: true,
  },
  {
    id: "mars-express",
    name: "Mars Express",
    agency: "ESA (European Space Agency)",
    craftType: "Orbiter",
    category: "mars",
    destination: "Mars (Polar Elliptical Orbit)",
    launchYear: 2003,
    status: "Active",
    missionDuration: "21+ years in orbit",
    missionPurpose: "Comprehensive exploration of Martian atmosphere, ionosphere, structure, and subsurface water reservoirs.",
    majorInstruments: ["MARSIS (Subsurface Sounding Radar)", "HRSC (High Resolution Stereo Camera)", "OMEGA (IR Spectrometer)", "SPICAM"],
    realSpecs: {
      launchMassKg: 1123,
      propulsion: "400 N main bipropellant engine (MON-3/MMH) + 8 reaction control thrusters",
      power: "Twin solar wings (650 W at aphelion) + Li-ion batteries",
      communication: "1.65-meter parabolic high-gain antenna (X-band and S-band)",
      propellantMassKg: 457,
    },
    gameModel: {
      engineClass: "Bipropellant Deep-Space Engine",
      massTier: "Medium European Explorer",
      powerType: "Dual Solar Wings",
      instrumentEquivalents: ["radar", "camera", "spectrometer"],
      simulationNotes: "Real-world host of the MARSIS radar system represented in the science instruments registry.",
    },
    whyItMatters: "Detected subglacial liquid water lakes beneath the south polar layered deposits and identified methane signatures in the atmosphere.",
    officialSource: "ESA Mars Express Mission Science Operations",
    sourceUrl: "https://www.esa.int/Science_Exploration/Space_Science/Mars_Express",
    verified: true,
  },
  {
    id: "maven",
    name: "MAVEN",
    agency: "NASA / GSFC / LASP",
    craftType: "Orbiter",
    category: "mars",
    destination: "Mars (Elliptical Orbit)",
    launchYear: 2013,
    status: "Active",
    missionDuration: "10+ years",
    missionPurpose: "Investigate how solar wind stripped Mars of its ancient atmosphere and volatile water over billions of years.",
    majorInstruments: ["SWEA (Solar Wind Electron Analyzer)", "STATIC (Suprathermal Ion Composition)", "IUVS (Imaging UV Spectrograph)", "MAG"],
    realSpecs: {
      launchMassKg: 2454,
      propulsion: "Hydrazine propulsion system (6 x 90 N thrusters + 6 x 22 N attitude thrusters)",
      power: "2 gull-wing solar panels with 2 kW output at 1 AU (~1 kW at Mars)",
      communication: "2-meter steerable high-gain antenna (X-band)",
      propellantMassKg: 1645,
    },
    gameModel: {
      engineClass: "Chemical Orbital Transfer Engine",
      massTier: "Atmospheric & Ionospheric Scout",
      powerType: "Twin Gull-Wing Solar Arrays",
      instrumentEquivalents: ["spectrometer", "radiation"],
      simulationNotes: "Models the space weather interaction between solar flares and thin planetary atmospheres during interplanetary transit.",
    },
    whyItMatters: "Proved that solar coronal mass ejections (CMEs) dramatically accelerate atmospheric stripping from Mars.",
    officialSource: "NASA MAVEN Mission Page",
    sourceUrl: "https://science.nasa.gov/mission/maven/",
    verified: true,
  },

  // --- ASTEROIDS & SMALL BODIES ---
  {
    id: "dawn",
    name: "Dawn",
    agency: "NASA / JPL",
    craftType: "Orbiter",
    category: "asteroids",
    destination: "Asteroid Belt (Vesta & Ceres)",
    launchYear: 2007,
    status: "Completed",
    missionDuration: "11 years (2007–2018)",
    missionPurpose: "Study the early solar system by orbiting and characterizing the two most massive protoplanets in the main asteroid belt: Vesta and Ceres.",
    majorInstruments: ["Framing Camera (FC)", "Visible and Infrared Spectrometer (VIR)", "Gamma Ray and Neutron Detector (GRaND)"],
    realSpecs: {
      launchMassKg: 1218,
      propulsion: "3 x NSTAR Xenon Ion Thrusters (Isp 3,100 s, max thrust 91 mN)",
      power: "Two 8.3-meter solar array wings (10 kW at 1 AU, 1.3 kW at Ceres)",
      communication: "1.52-meter parabolic High Gain Antenna (X-band)",
      propellantMassKg: 425,
    },
    gameModel: {
      engineClass: "Ion Propulsion Engine (NSTAR, Isp 3,100 s in Mission Forge)",
      massTier: "Solar-Electric Deep Space Craft",
      powerType: "Ultra-High Area Solar Wings",
      instrumentEquivalents: ["camera", "spectrometer", "radiation"],
      simulationNotes: "Dawn is the exact real-world prototype for Mission Forge's high-efficiency Ion engine choice.",
    },
    whyItMatters: "First and only spacecraft to orbit two separate extraterrestrial destinations (Vesta 2011–2012, Ceres 2015–2018). Discovered water vapor ice and sodium carbonate brine mounds in Occator Crater.",
    officialSource: "NASA JPL Dawn Mission Archive",
    sourceUrl: "https://science.nasa.gov/mission/dawn/",
    verified: true,
  },
  {
    id: "osiris-rex",
    name: "OSIRIS-REx / OSIRIS-APEX",
    agency: "NASA / GSFC / Univ of Arizona",
    craftType: "Lander / Rover",
    category: "asteroids",
    destination: "Near-Earth Asteroid (101955 Bennu & Apophis)",
    launchYear: 2016,
    status: "Active",
    missionDuration: "8+ years (sample returned 2023; now en route to Apophis)",
    missionPurpose: "Map carbonaceous asteroid Bennu, collect a pristine surface regolith sample using TAGSAM, return it to Earth, and cruise to Apophis.",
    majorInstruments: ["OCAMS Camera Suite", "OVIRS Spectrometer", "OTES Thermal Spectrometer", "OLA (Laser Altimeter)", "TAGSAM (Sample arm)"],
    realSpecs: {
      launchMassKg: 2110,
      propulsion: "Aerojet Rocketdyne hydrazine monopropellant system (4 x 200 N + 16 x 22 N)",
      power: "Dual solar arrays (1,226 W to 3,000 W depending on solar distance)",
      communication: "2-meter parabolic High Gain Antenna (X-band)",
      propellantMassKg: 1230,
    },
    gameModel: {
      engineClass: "Chemical Monopropellant Maneuvering Engine",
      massTier: "Asteroid Sample Return Craft",
      powerType: "Dual Solar Arrays",
      instrumentEquivalents: ["camera", "spectrometer", "radar", "drill"],
      simulationNotes: "Corresponds to the Asteroid Survey & Touchdown mission profile in Mission Forge.",
    },
    whyItMatters: "Delivered 121.6 grams of carbon- and water-rich asteroid sample to Utah in September 2023, the largest extraterrestrial sample brought home since Apollo.",
    officialSource: "NASA OSIRIS-REx Mission Site",
    sourceUrl: "https://science.nasa.gov/mission/osiris-rex/",
    verified: true,
  },
  {
    id: "psyche",
    name: "Psyche",
    agency: "NASA / JPL / ASU",
    craftType: "Orbiter",
    category: "asteroids",
    destination: "Main Belt Asteroid (16 Psyche)",
    launchYear: 2023,
    status: "En Route",
    missionDuration: "6-year transit to Psyche (arrival August 2029)",
    missionPurpose: "Explore a unique metal-rich M-type asteroid thought to be the exposed metallic core of an early protoplanet.",
    majorInstruments: ["Multispectral Imager", "Gamma Ray and Neutron Spectrometer", "Magnetometer", "Deep Space Optical Communications (DSOC)"],
    realSpecs: {
      launchMassKg: 2747,
      propulsion: "SPT-140 Hall-effect electric thrusters (Isp ~1,800 s, thrust 240 mN)",
      power: "Cross-shaped dual solar arrays (21 kW at 1 AU, 2.4 kW at Psyche)",
      communication: "X-band High Gain Antenna + laser optical communications (DSOC)",
      propellantMassKg: 1085,
    },
    gameModel: {
      engineClass: "Hall Thruster (HERMeS / SPT analog in Mission Forge)",
      massTier: "Heavy Electric Propulsion Probe",
      powerType: "Cross-Configured High-Area Solar Wings",
      instrumentEquivalents: ["camera", "spectrometer", "radiation"],
      simulationNotes: "Embodies the Hall Thruster engine in Mission Forge, which balances higher thrust than gridded ion engines with high fuel economy.",
    },
    whyItMatters: "First mission to study a world made not of rock or ice, but largely of nickel and iron metal.",
    officialSource: "NASA JPL Psyche Mission Page",
    sourceUrl: "https://science.nasa.gov/mission/psyche/",
    verified: true,
  },
  {
    id: "hayabusa2",
    name: "Hayabusa2",
    agency: "JAXA (Japan Aerospace Exploration Agency)",
    craftType: "Lander / Rover",
    category: "asteroids",
    destination: "Asteroid (162173 Ryugu)",
    launchYear: 2014,
    status: "Active",
    missionDuration: "Returned sample in 2020; extended mission to 2031",
    missionPurpose: "Sample collection and impactor cratering experiment on C-type near-Earth asteroid Ryugu, delivering pristine samples to Earth.",
    majorInstruments: ["Optical Navigation Camera", "Near-Infrared Spectrometer (NIRS3)", "TIR (Thermal Infrared)", "Small Carry-on Impactor (SCI)"],
    realSpecs: {
      launchMassKg: 609,
      propulsion: "4 x microwave discharge ion engines (Isp ~3,000 s) + hydrazine/MON RCS",
      power: "Twin solar wings (~1,400 W at 1 AU)",
      communication: "High-gain Ka-band and X-band parabolic antenna",
      propellantMassKg: 66,
    },
    gameModel: {
      engineClass: "Ion Propulsion + Kinetic Impactor",
      massTier: "Compact Sample Return Craft",
      powerType: "High-Efficiency Solar Wings",
      instrumentEquivalents: ["camera", "spectrometer", "drill"],
      simulationNotes: "JAXA's signature solar-electric sample return benchmark.",
    },
    whyItMatters: "Proved that C-type asteroids contain indigenous amino acids and prebiotic organic compounds essential to the emergence of life.",
    officialSource: "JAXA Hayabusa2 Project Site",
    sourceUrl: "https://www.isas.jaxa.jp/en/missions/spacecraft/current/hayabusa2.html",
    verified: true,
  },

  // --- JUPITER ---
  {
    id: "europa-clipper",
    name: "Europa Clipper",
    agency: "NASA / JPL / APL",
    craftType: "Orbiter",
    category: "jupiter",
    destination: "Jupiter & Europa",
    launchYear: 2024,
    status: "En Route",
    missionDuration: "5.5-year cruise to Jupiter (arrival April 2030), 49 Europa flybys",
    missionPurpose: "Investigate whether the icy Jovian moon Europa could harbor conditions suitable for extraterrestrial life within its sub-surface ocean.",
    majorInstruments: ["REASON (Ice-Penetrating Radar)", "MISE (IR Spectrometer)", "Europa-UVS", "EIS (Imaging System)", "MASPEX (Gas Spectrometer)", "SUDA", "ECM (Magnetometer)"],
    realSpecs: {
      launchMassKg: 6000,
      propulsion: "Bipropellant MMH / MON-3 main propulsion + 24 attitude control thrusters",
      power: "Massive twin solar arrays spanning over 30 meters (700 W at Jupiter, 5.2 AU)",
      communication: "3-meter High Gain Antenna (Ka-band and X-band)",
      propellantMassKg: 2750,
    },
    gameModel: {
      engineClass: "Chemical Bipropellant Deep-Space Engine",
      massTier: "Flagship Deep Space Craft (~6,000 kg)",
      powerType: "Giant Solar Array Wings (6 wings in Mission Forge)",
      instrumentEquivalents: ["radar", "spectrometer", "camera", "radiation"],
      simulationNotes: "Illustrates the steep inverse-square sunlight penalty at Jupiter, where 6 full solar wings are required to meet baseline power demand.",
    },
    whyItMatters: "Largest planetary exploration spacecraft NASA has ever developed, carrying advanced sounding radar to penetrate Europa's 15–25 km thick ice shell.",
    officialSource: "NASA Europa Clipper Science Mission",
    sourceUrl: "https://science.nasa.gov/mission/europa-clipper/",
    verified: true,
  },
  {
    id: "juno",
    name: "Juno",
    agency: "NASA / JPL / SwRI",
    craftType: "Orbiter",
    category: "jupiter",
    destination: "Jupiter (Polar Orbit)",
    launchYear: 2011,
    status: "Active",
    missionDuration: "13+ years (entered Jupiter orbit 2016; active extended mission)",
    missionPurpose: "Probe beneath Jupiter's dense clouds to measure deep atmospheric water, gravitational harmonics, magnetic field structure, and magnetosphere.",
    majorInstruments: ["JunoCam", "MWR (Microwave Radiometer)", "MAG (Fluxgate Magnetometer)", "JEDI", "JADE", "Waves"],
    realSpecs: {
      launchMassKg: 3625,
      propulsion: "Leros-1b bipropellant main engine (645 N thrust) + hydrazine RCS",
      power: "3 solar array wings spanning 20 meters (480 W at Jupiter)",
      communication: "2.5-meter High Gain Antenna (X-band and Ka-band)",
      propellantMassKg: 2032,
    },
    gameModel: {
      engineClass: "Chemical Cryogenic / Bipropellant",
      massTier: "Heavy Radiation-Hardened Explorer",
      powerType: "Triple Solar Array Wings",
      instrumentEquivalents: ["camera", "spectrometer", "radiation"],
      simulationNotes: "Features a titanium radiation vault to survive Jupiter's extreme radiation belt, which matches Mission Forge's Whipple Shield mitigation mechanic.",
    },
    whyItMatters: "First mission to operate on solar power at Jupiter, discovering that Jupiter has a fuzzy, diluted core and massive atmospheric cyclone clusters.",
    officialSource: "NASA JPL Juno Mission",
    sourceUrl: "https://science.nasa.gov/mission/juno/",
    verified: true,
  },
  {
    id: "galileo",
    name: "Galileo",
    agency: "NASA / JPL",
    craftType: "Orbiter",
    category: "jupiter",
    destination: "Jupiter & Galilean Moons",
    launchYear: 1989,
    status: "Completed",
    missionDuration: "14 years (1989–2003)",
    missionPurpose: "First spacecraft to orbit Jupiter and deploy an atmospheric descent probe into a gas giant's atmosphere.",
    majorInstruments: ["Solid-State Imager (SSI)", "NIMS (Infrared Spectrometer)", "UVS", "Magnetometer", "Heavy Ion Counter", "Atmospheric Entry Probe"],
    realSpecs: {
      launchMassKg: 2562,
      propulsion: "400 N bipropellant main engine + 12 x 10 N thrusters",
      power: "2 x GPHS-RTG units (570 W at launch) — solar unfeasible in 1989",
      communication: "Low Gain Antenna (High Gain failed to deploy fully; commanded via 10–40 bps fallback)",
      propellantMassKg: 959,
    },
    gameModel: {
      engineClass: "Bipropellant Main Engine",
      massTier: "Deep Space Flagship",
      powerType: "Plutonium-238 RTG (2 units)",
      instrumentEquivalents: ["camera", "spectrometer", "radiation"],
      simulationNotes: "Exemplifies the rescue and comms-failure scenarios modeled in Mission Forge when antenna deployment encounters glitches.",
    },
    whyItMatters: "Confirmed global subsurface oceans beneath Europa's ice and liquid water under Callisto and Ganymede; observed the impact of Comet Shoemaker-Levy 9.",
    officialSource: "NASA JPL Galileo Legacy",
    sourceUrl: "https://science.nasa.gov/mission/galileo/",
    verified: true,
  },

  // --- SATURN ---
  {
    id: "cassini-huygens",
    name: "Cassini-Huygens",
    agency: "NASA / ESA / ASI",
    craftType: "Orbiter",
    category: "saturn",
    destination: "Saturn & Moons (Titan & Enceladus)",
    launchYear: 1997,
    status: "Completed",
    missionDuration: "20 years (1997–2017)",
    missionPurpose: "Profoundly transform human knowledge of Saturn, its rings, complex magnetosphere, and ocean moons Titan and Enceladus.",
    majorInstruments: ["VIMS (Visual & IR Spectrometer)", "CIRS (Composite IR)", "ISS (Imaging Science Subsystem)", "RADAR", "MAG", "INMS", "Huygens Titan Probe"],
    realSpecs: {
      launchMassKg: 5712,
      propulsion: "2 x 445 N R-4D bipropellant engines + 16 hydrazine RCS thrusters",
      power: "3 x GPHS-RTG units (885 W at launch, 633 W at Grand Finale)",
      communication: "4-meter High Gain parabolic dish antenna (X-band and Ku-band)",
      propellantMassKg: 3132,
    },
    gameModel: {
      engineClass: "Bipropellant Flagship Engine",
      massTier: "Flagship Heavy Class (~5,700 kg)",
      powerType: "3x RTG Architecture (mandatory at 9.5 AU)",
      instrumentEquivalents: ["camera", "spectrometer", "radar", "radiation"],
      simulationNotes: "Validates Mission Forge's rule that missions beyond 5 AU require RTGs, because solar flux falls to ~1% of Earth levels.",
    },
    whyItMatters: "Discovered active hydrothermal cryovolcanoes spewing water and organics from Enceladus and deployed the Huygens probe to the surface of Titan.",
    officialSource: "NASA JPL Cassini Mission Page",
    sourceUrl: "https://science.nasa.gov/mission/cassini/",
    verified: true,
  },

  // --- OUTER SOLAR SYSTEM ---
  {
    id: "voyager-1",
    name: "Voyager 1 & 2",
    agency: "NASA / JPL",
    craftType: "Flyby",
    category: "outer",
    destination: "Jupiter, Saturn, Uranus, Neptune & Interstellar Space",
    launchYear: 1977,
    status: "Interstellar",
    missionDuration: "49+ years (continuous operation since 1977)",
    missionPurpose: "Conduct a historic grand-tour flyby reconnaissance of Jupiter, Saturn, Uranus, and Neptune, and explore the interstellar heliopause boundary.",
    majorInstruments: ["Cosmic Ray System (CRS)", "Low Energy Charged Particle (LECP)", "Magnetometer (MAG)", "Plasma Wave System (PWS)", "Imaging Science (ISS)"],
    realSpecs: {
      launchMassKg: 815,
      propulsion: "Hydrazine monopropellant thrusters (104 kg fuel) + solid rocket burnout kick",
      power: "3 x MHW-RTG units (470 W at launch, currently ~220 W via half-life decay)",
      communication: "3.7-meter High Gain dish antenna direct to DSN (23 W transmitter)",
      propellantMassKg: 104,
    },
    gameModel: {
      engineClass: "Gravity-Assist Cruise + Hydrazine Micro-Thrusters",
      massTier: "Lightweight Deep Space Scout (815 kg)",
      powerType: "Plutonium-238 RTG (Long-life nuclear battery)",
      instrumentEquivalents: ["radiation", "camera", "spectrometer"],
      simulationNotes: "Direct real-world basis for the 'Gravity Assist' route option in Mission Forge, which reduces fuel load by borrowing planetary momentum.",
    },
    whyItMatters: "Farthest human-made object in history (>162 AU from Earth, >24 billion km). Entered interstellar space in August 2012.",
    officialSource: "NASA JPL Voyager Interstellar Mission",
    sourceUrl: "https://voyager.jpl.nasa.gov/",
    verified: true,
  },
  {
    id: "new-horizons",
    name: "New Horizons",
    agency: "NASA / APL / SwRI",
    craftType: "Flyby",
    category: "outer",
    destination: "Pluto, Charon & Kuiper Belt (Arrokoth)",
    launchYear: 2006,
    status: "Active",
    missionDuration: "18+ years (flew past Pluto in 2015, Arrokoth in 2019)",
    missionPurpose: "First reconnaissance of the Pluto system and primitive planetesimals in the Kuiper Belt at the outer edge of the solar system.",
    majorInstruments: ["LORRI (High-resolution imager)", "Ralph (Color imager & IR spectrometer)", "Alice (UV spectrometer)", "REX (Radio science)", "SWAP", "PEPSSI"],
    realSpecs: {
      launchMassKg: 478,
      propulsion: "16 x hydrazine monopropellant thrusters (77 kg propellant)",
      power: "1 x GPHS-RTG (~240 W at launch, ~190 W at Pluto)",
      communication: "2.1-meter parabolic High Gain Antenna (X-band ~1 kbps at Pluto)",
      propellantMassKg: 77,
    },
    gameModel: {
      engineClass: "Direct Insertion + Micro-Hydrazine Reaction Control",
      massTier: "Ultra-Lightweight Fast Flyby Probe (<500 kg)",
      powerType: "Single Radioisotope Generator (RTG)",
      instrumentEquivalents: ["camera", "spectrometer", "radiation"],
      simulationNotes: "Fastest spacecraft ever launched from Earth (relative to Earth at 16.26 km/s), illustrating the high-speed transfer mechanics.",
    },
    whyItMatters: "Transformed humanity's understanding of Pluto, revealing active nitrogen glaciers, water-ice mountains, and blue atmospheric haze.",
    officialSource: "NASA New Horizons Science Mission",
    sourceUrl: "https://science.nasa.gov/mission/new-horizons/",
    verified: true,
  },

  // --- SPACE TELESCOPES ---
  {
    id: "jwst",
    name: "James Webb Space Telescope (JWST)",
    agency: "NASA / ESA / CSA",
    craftType: "Space Observatory",
    category: "telescopes",
    destination: "Sun-Earth L2 Lagrange Point (~1.5M km)",
    launchYear: 2021,
    status: "Active",
    missionDuration: "20-year planned lifetime",
    missionPurpose: "Investigate every phase of cosmic history, from the first luminous glows after the Big Bang to the formation of solar systems capable of supporting life.",
    majorInstruments: ["NIRCam (Near-IR Camera)", "NIRSpec (Near-IR Spectrograph)", "MIRI (Mid-IR Instrument)", "FGS/NIRISS (Fine Guidance Sensor)"],
    realSpecs: {
      launchMassKg: 6161,
      propulsion: "SCAT secondary combustion augmented thrusters (hydrazine / dinitrogen tetroxide)",
      power: "Deployable 5-panel solar array (2.0 kW) + Li-ion battery",
      communication: "0.6-meter High Gain Ka-band steerable dish (28 Mbps)",
      propellantMassKg: 301,
    },
    gameModel: {
      engineClass: "Stationkeeping Monopropellant / Bipropellant",
      massTier: "Flagship Observatory Class",
      powerType: "Deployable Solar Array + 5-Layer Sunshield",
      instrumentEquivalents: ["camera", "spectrometer"],
      simulationNotes: "Requires ultra-stable thermal management at L2, corresponding to Mission Forge's Thermal Equilibrium rules.",
    },
    whyItMatters: "Most powerful space telescope ever constructed, utilizing a 6.5-meter gold-coated beryllium mirror to observe high-redshift early galaxies.",
    officialSource: "NASA Webb Space Telescope Mission",
    sourceUrl: "https://webb.nasa.gov/",
    verified: true,
  },
  {
    id: "hubble",
    name: "Hubble Space Telescope (HST)",
    agency: "NASA / ESA",
    craftType: "Space Observatory",
    category: "telescopes",
    destination: "Low Earth Orbit (540 km)",
    launchYear: 1990,
    status: "Active",
    missionDuration: "34+ years in continuous operation",
    missionPurpose: "Provide deep, diffraction-limited astronomical imagery across ultraviolet, visible, and near-infrared bands from above Earth's obscuring atmosphere.",
    majorInstruments: ["WFC3 (Wide Field Camera 3)", "COS (Cosmic Origins Spectrograph)", "ACS (Advanced Camera for Surveys)", "STIS"],
    realSpecs: {
      launchMassKg: 11110,
      propulsion: "Zero propellant thrusters — relies entirely on 4 reaction wheels and magnetic torquers",
      power: "2 solar wings (5.5 kW at beginning of life) + 6 nickel-hydrogen batteries",
      communication: "2 steerable parabolic High Gain Antennas via TDRSS satellites (S-band)",
    },
    gameModel: {
      engineClass: "Reaction Wheel Inertial Attitude Control (No chemical thrusters)",
      massTier: "Heavy Space Telescope (~11,100 kg)",
      powerType: "Dual Solar Arrays + Battery Storage",
      instrumentEquivalents: ["camera", "spectrometer"],
      simulationNotes: "Serviced 5 times by astronauts via the Space Shuttle, proving that in-space repair and modular maintenance are physically feasible.",
    },
    whyItMatters: "Determined the expansion rate of the universe (Hubble constant), discovered that almost all major galaxies contain supermassive black holes.",
    officialSource: "NASA Hubble Site Fact Sheet",
    sourceUrl: "https://science.nasa.gov/mission/hubble/",
    verified: true,
  },
];
